class Currencies {
  List<String> curr = [
    'Bitcoin',
    'Tether',
    'Ethereum',
    'Ripple',
    'Binance Coin',
    'Cardano',
    'Dogecoin',
    'HEX',
    'USD Coin',
    'Polkadot',
    'Dfinity',
    'Uniswap Protocol Token',
    'Bitcoin Cash',
    'ChainLink',
    'Litecoin',
    'Polygon',
    'Binance USD',
    'Stellar',
    'Ethereum Classic',
    'Shiba Inu',
    'Solana',
    'Wrapped Bitcoin',
    'VeChain Thor',
    'Theta Token',
    'EOS',
    'Filecoin',
    'TRON',
    'Dai',
    'Algorand',
    'Monero',
    'Aave',
    'FTX Token',
    'Compound USD Coin',
    'NEO',
    'Klaytn',
    'OKEx Utility Token',
    'Compound Ether',
    'Bitcoin SV',
    'Celsius',
    'Cosmos',
    'Crypto.com Chain',
    'Maker',
    'IOTA (MIOTA)',
    'Tezos',
    'Huobi Token',
    'PancakeSwap',
    'Thorchain',
    'Kusama',
    'BitTorrent',
    'SafeMoon',
    'Sushi',
    'Luna',
    'Avalanche',
    'TerraUSD',
    'UNUS SED LEO',
    'Compound',
    'Dash',
    'Hedera Hashgraph',
    'Decred',
    'Synthetix Network Token',
    'Zcash',
    'Elrond',
    'Theta Fuel',
    'AMP Token',
    'NEM',
    'The Transfer Token',
    'Helium',
    'Chiliz',
    'Telcoin',
    'yearn.finance',
    'Holo',
    'TrueUSD',
    'Paxos Standard',
    'Waves',
    'Horizen',
    'Enjin Coin',
    'Zilliqa',
    'WhiteCoin',
    'Qtum',
    'Huobi BTC',
    'Stacks',
    'Bitcoin Gold',
    'Near Protocol',
    'Basic Attention Token',
    'Liquid Staked Ether',
    'Nexo',
    'Decentraland',
    'Fundum',
    'Ontology',
    'Nano',
    'Bancor',
    'OMG Network',
    'DigiByte',
    'Harmony',
    'The Graph',
    'Siacoin',
    'UMA',
    'Fantom',
    'Gatechain Token',
  ];
}
